apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-api-demo-secret
  namespace: sample-api
spec:
  encryptedData:
    DEMO_VALUE: PLACEHOLDER_GENERATED_BY_KUBESEAL
  template:
    metadata:
      name: sample-api-demo-secret
      namespace: sample-api
    type: Opaque
