apiVersion: v1
kind: Secret
metadata:
  name: clipproxy-secret
  namespace: clipproxy
type: Opaque
stringData:
  CPA_MANAGER_ADMIN_KEY: example-admin-key-change-me
  CPA_MANAGEMENT_KEY: example-management-key-change-me
