resources:
  - configmap.yaml
  - pvc-api.yaml
  - deployment-api.yaml
  - service-api.yaml
  - pvc-manager.yaml
  - deployment-manager.yaml
  - service-manager.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: clipproxy
      app.kubernetes.io/part-of: rancher-platform-template
